# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c6fc3c78476aac6a25829b0d7c04200"
name = "payment-extension"
handle = "payment-extension-7"
application_url = "https://sponsorship-understood-nextel-britain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a159a43a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sponsorship-understood-nextel-britain.trycloudflare.com/auth/callback",
  "https://sponsorship-understood-nextel-britain.trycloudflare.com/auth/shopify/callback",
  "https://sponsorship-understood-nextel-britain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
