api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "payment-ext-function"
type = "function"

description = "t:description"

[[extensions.targeting]]
target = "purchase.payment-customization.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = ""
path = "dist/function.wasm"

[extensions.ui.paths]
create = "/app/payment-ext-function/:functionId/new"
details = "/app/payment-ext-function/:functionId/:id"
